# Generated by Django 4.2.10 on 2024-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_remove_transaction_wallet_transaction_user_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
    ]
