# Generated by Django 4.2.10 on 2024-02-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_transaction_source_transaction_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
