# Generated by Django 4.2.10 on 2024-02-23 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_transaction_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(default='', max_length=255)),
                ('acc_currency', models.CharField(default='', max_length=255)),
                ('acc_leverage', models.CharField(default='', max_length=255)),
                ('islamic', models.BooleanField(default=False)),
                ('master_pass', models.CharField(default='', max_length=255)),
                ('investor_pass', models.CharField(default='', max_length=255)),
                ('nickname', models.CharField(blank=True, default='', max_length=255)),
                ('balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
