# Generated by Django 4.2.10 on 2024-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_ticket_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_baned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='from_admin',
            field=models.BooleanField(default=False),
        ),
    ]
