# Generated by Django 4.2.10 on 2024-02-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_customuser_is_baned_messages_from_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
