# Generated by Django 4.2.10 on 2024-03-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_transaction_comment_verificationdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hidden_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hidden_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
