# Generated by Django 4.2.10 on 2024-03-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_ticket_hidden_admin_ticket_hidden_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
