# Generated by Django 4.2.10 on 2024-03-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_confirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
